Include changes object key in display name.
mobxjs/mobx-devtools pull request #46
Opened 2019-02-17 02:37 UTC by denniskempin

This makes change logs more useful by including which field of an object
may have changed instead of just mentioning the objects name.

Example screenshot:
![screenshot from 2019-02-16 18-33-30](https://user-images.githubusercontent.com/7072461/52907607-9791d980-3219-11e9-933d-0b61a9d26715.png)

Let me know what you think. I found this very helpful when using mobx-devtools.

2019-03-09 13:29 UTC, andykog requested changes
Getting runtime error because utils.js doesn't have named export `changeDisplayName`

2019-09-08 17:00 UTC, anikethsaha requested changes
Left few changes

2019-09-08 17:00 UTC, anikethsaha commented on src/frontend/TabChanges/LObjDiff.jsx
> +import { changeDisplayName } from './utils';
```suggestion
import changeDisplayName from './utils';
```

2019-09-08 17:00 UTC, anikethsaha commented on src/frontend/TabChanges/LObjDiff.jsx
> +import { changeDisplayName } from './utils';
As its exporting as a default !

2019-09-08 17:00 UTC, anikethsaha commented on src/frontend/TabChanges/utils.js
> +export default function changeDisplayName(change) {
may be its better to keep the `utils` in the `frontend` instead of `frontend/tabChanges/`

2019-11-02 14:25 UTC, kubk commented
Hi @denniskempin , such a useful feature, thank you! Do you plan to continue working on it?

2022-07-02 22:05 UTC, closed without merging