Type Definition
mobxjs/mobx-devtools pull request #81
Opened 2020-10-18 05:54 UTC by kuasha420

Fixes #67

2020-10-18 10:37 UTC, epodgaetskiy requested changes
Please merge master, and remove everything with dependencies.

2020-10-18 10:37 UTC, epodgaetskiy commented on packages/mobx-devtools-mst/types/index.d.ts
> +  export default function makeInspectable(state: object): void;
```suggestion
  type Root = object;
  export default function makeInspectable(root: Root): Root;
```

2020-10-18 12:03 UTC, kuasha420 commented
@epodgaetskiy Everything ok? Monorepo always trips me off..

BTW, eslint is failing on precommit hook, had no --no-verify it. The error is about unresolved electron import on `mobx-devtools/packages/playground/electron/background.js`

2020-10-18 12:23 UTC, epodgaetskiy commented
> @epodgaetskiy Everything ok? Monorepo always trips me off..
> 
> BTW, eslint is failing on precommit hook, had no --no-verify it. The error is about unresolved electron import on `mobx-devtools/packages/playground/electron/background.js`

Thank you. I fixed it. Please merge master.

2020-10-19 01:40 UTC, kuasha420 commented
@epodgaetskiy Done.

2020-10-19 10:06 UTC, merged